title: Liz Barron
#logo: /assets/img/2.png
description: e-Learning & xAPI Consultant | Instructional Technology - Learning & Development - Front-end Web Development <br>Leveraging technology to streamline workflows & develop engaging learning experiences
#show_downloads: true
theme: jekyll-theme-minimal
