title: Liz Barron
#logo: /assets/img/2.png
description: <b>e-Learning & xAPI Consultant</b><br><em>Leveraging technology to streamline workflows & develop engaging learning experiences</em>
#show_downloads: true
theme: jekyll-theme-minimal
