title: Liz Barron
#logo: /assets/img/2.png
description: <em>e-Learning & xAPI Consultant</em><br>Leveraging technology to streamline workflows & develop engaging learning experiences
#show_downloads: true
theme: jekyll-theme-minimal
