title: Liz Barron
#logo: /assets/img/2.png
description: <p><b>e-Learning & xAPI Consultant</b><br><em>Leveraging technology to streamline workflows & develop engaging learning experiences</em><br><a href="https://www.linkedin.com/in/liz-barron/">View my LinkedIn Profile<small>https://www.linkedin.com/in/liz-barron/</small></p>
#show_downloads: true
theme: jekyll-theme-minimal
